name: mitos_y_leyendas_app
description: "App Para mostrar cartas del TCG Mitos y leyendas"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.7

  auto_size_text: ^3.0.0
  dio: ^5.9.0
  flutter_riverpod: ^3.0.3
  go_router: ^17.0.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

# CONFIGURACIÃ“N DEL SPLASH
flutter_native_splash:
  android: true
  ios: false
  web: false

  color: "#FFFFFF"
  image: assets/images/myl_logo.png

  android_12:
    color: "#FFFFFF"
    image: assets/images/myl_logo.png
